---
title: "Linear day 1"
author: "Kurt"
date: "2024-07-15"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
ggplot(mtcars, aes(mpg,cyl))+geom_jitter()
```

```{r}
OurData <- read.csv('ClassData.csv')
ourData5<-OurData %>%
  mutate(slp=as.numeric(Sleep_Hrs))
t.test(ourData5$slp)
```
bootstraping
```{r}
mean_calc<-function(x){
  return(mean(x, na.rm = TRUE))
}
bootstrapMeans <- replicate(10000, {
bootstrap <- sample(ourData5$slp, replace = T)
mean_calc(bootstrap)
})
bootDf <- data.frame(bootstrapMeans)
head(bootDf)
ggplot(bootDf,aes(bootstrapMeans))+ geom_density()
```

```{r}
quantile(bootstrapMeans, c(0.025,0.975))
```

```{r}
prop.test(40,100,p=0.85,alternative = "l")
```


```{r}
t.test(ourData5$slp,mu=6)
t.test(ourData5$slp,mu=6, alternative = "greater")
```
```{r}
nba <- read.csv('nba.csv')
table(nba$W.L,nba$home_away)
```
Succsess over total
```{r}
prop.test(c(518,712),c(1230,1230))
```
They are 95% confident that for all nba games the away wins are between 11.8-19.8 percentage points less than the home wins.
```{r}
ggplot(nba, aes(home_away, fill = W.L)) + geom_bar(position = 'fill')
```

Average points won between home and away games
```{r}
t.test(PTS~home_away, data=nba)
```
We are 95% confident that the average points scored in all nba games  is 1.155093 - 3.056289 more points higher in home games than in road games

```{r}
ggplot(nba, aes(home_away,PTS, fill = home_away)) + geom_violin()+ geom_jitter()
```

```{r}
class2 <- mutate(OurData, AgeDiff = as.numeric(gsub("years","",Age_Diff_Parents)))
view(class2)
t.test(class2$AgeDiff)
```
Thursday
```{r}
CT <- read.csv("Clinical_trial.csv")
head(CT)
```
Anova 
```{r}
anovaCT <- aov(Pain_Rating~Drug, data = CT)
summary(anovaCT)
```


```{r}
TurkeyHSD(anovaCT,conf.level = 0.95)
```

```{r}

```

